---
# Defines tasks to install and configure Postfix

# Variable configuration.
- include: variables.yml

- include: debian_install.yml
  when: ansible_os_family == 'Debian'
  static: no

- include: configuration.yml
  static: no

- include: database_install.yml
  when: postfix_use_virtual_user 
  static: no

- name: Start Postfix on server boot
  service: >
    name="{{ postfix_service }}"
    state=started
    enabled=yes
  tags:
    - common
    - postfix
